# Generated by Django 3.0.9 on 2020-11-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201101_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highscore',
            options={'ordering': ['-score']},
        ),
    ]
